version: "3"
services:
  dynamic-thread-pool-web:
    container_name: dynamic-thread-pool-web
    image: registry.cn-heyuan.aliyuncs.com/coding_01/dynamic-thread-pool-web:1.3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - REACT_APP_DYNAMIC_HOST=http://localhost:8089
    volumes:
      - ./data:/app/data
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
